# Data transformation

To begin, much of our key electric vehicle data was formatted with inconvenient variable names, so we made use of a custom function to reformat them into more usable forms. In addition, we formatted date data and made use of a combination of piping and grouping to get counts for rebates.

Next, we reshape our recycling data to be grouped by borough, using the median zone rates to represent the typical for each borough. We also create a second month variable for ease of access.

Further, the key dataset used for NYC building energy usage was missing key data. Specifically, not all observations had the borough field populated, and it had nothing on the previously mentioned 2D square footage. As such, the first step in our data transformation was merging the dataset with the zip-boroughs mapping (df_zips, trimmed to be only zip and borough) and land-use datasets (df_area_full) in order to access this desired information:

In addition, the key greenhouse gas (ghg) field had to be converted to a numeric for manipulation and interpretation. After this, we reshaped the data for further by grouping by borough and zip code and taking both the mean and median GHG emissions for each. As previously noted, a singul negative value for GHG emissions was found. It is filtered out here, as well.

```{r include = FALSE}
library(tidyverse)
library(base)
library(zoo)
library(lubridate)
library(ggplot2)
library(latex2exp)

# from resources.xlsx
# ev_charging_use_data = resources_sheets$`Charging Use`

# use clean_rebate_data instead - more up to date but same thing
# ev_rebate_data = resources_sheets$`Drive Clean Rebate`

# from EV-Registration-Tables.xlsx
ev_zip_code_data = ev_registration_tables_sheets$`Current by ZIP Code`
ev_make_model_data = ev_registration_tables_sheets$`Current by Make-Model`
ev_county_data = ev_registration_tables_sheets$`Current by County`
ev_over_time_data = ev_registration_tables_sheets$`Original Over Time`
ev_make_over_time = ev_registration_tables_sheets$`Original by Make`

cleanCols <- function(x){
  lower_names = tolower(names(x))
  sub_periods = gsub("\\.", "_", lower_names)
  sub_spaces = gsub(" ","_",sub_periods)
  clean_df_cols = gsub("__","_",sub_spaces)
  return(clean_df_cols)
}

names(global_electric_car_sales_data) = cleanCols(global_electric_car_sales_data)
names(energy_programs_data) = cleanCols(energy_programs_data)
names(emissions_from_fuel_data) = cleanCols(emissions_from_fuel_data)
names(fuel_emission_factors_data) = cleanCols(fuel_emission_factors_data)
names(clean_rebate_data) = cleanCols(clean_rebate_data)
# names(ev_registrations_data) = cleanCols(ev_registrations_data)
#names(federal_cvrp_stats) = cleanCols(federal_cvrp_stats)
#NOTE - IDK WHAT IS GOING ON WITH CVRP LARRIES
#names(ev_rebate_data) = cleanCols(ev_rebate_data)
#NOTE - I DON'T SEE AN EV REBATE LARRY IN THE DATA SECTIONS

# ev_original_registrations_data = filter(ev_registrations_data, registration == 'Original')

clean_rebate_data$date = as.Date(clean_rebate_data$submitted_date, "%m/%d/%Y")
clean_rebate_data$year = format(clean_rebate_data$date, format="%Y")
clean_rebate_data$year_quarter <- as.yearqtr(clean_rebate_data$date, format = "%Y-%m-%d")

clean_rebate_data$cumulative_rebate_amount = cumsum(clean_rebate_data$rebate_amount_usd_)

# count by quarter
clean_rebate_counts = clean_rebate_data %>% group_by(year_quarter) %>% tally()

# by quarter
clean_rebate_data_by_quarter = aggregate(clean_rebate_data$rebate_amount_usd_,
                                         by=list(clean_rebate_data$year_quarter),
                                         FUN=sum)
#IDK WHY BUT YEAR_QUARTER WAS LOSING ITS NAME - ADDING HERE
clean_rebate_data_by_quarter$year_quarter = clean_rebate_data_by_quarter$`Group.1`
clean_rebate_data_by_quarter$rebate_amount = clean_rebate_data_by_quarter$x

clean_rebate_data_by_quarter$cumulative_rebate_amount = cumsum(clean_rebate_data_by_quarter$rebate_amount)
#SEEING A WEIRD ERROR ABOUT "REPLACEMENT HAS 0 ROWS, DATAS 17 CALLS
clean_rebate_data_by_quarter$count = clean_rebate_counts$n



names(df_rec) = cleanCols(df_rec)
df_rec$month  = df_rec$month_name

rec_use <- df_rec %>% group_by(zone, month) %>% 
  summarise(capture_rate = median(capture_rate_total__total_recycling__leaves_recycling___max_paper__max_mgp_x100),
            paper_rate = median(capture_rate_paper_total_paper__max_paper_),
            mgp_rate = median(capture_rate_mgp_total_mgp__max_mgp_),
            diversion_rate = median(diversion_rate_total_total_recycling__total_waste_))


rec_use$month <- factor(rec_use$month, levels = c("January", "February", "March", "April",
                                                  "May", "June", "July", "August", "September",
                                                  "November", "December"))

df_zips <- df_zips[c(1, 2)]

df_area_full$building_area = df_area_full$bldgfront * df_area_full$bldgdepth 
df_area <- df_area_full[c(69, 100)]

df_build_energy = df_build_energy_source

names(df_build_energy) = cleanCols(df_build_energy)
df_build_energy$zip <- df_build_energy$postal_code
df_build_energy <- merge(df_build_energy, df_zips, by = "zip")

df_build_energy <- merge(x = df_build_energy, y = df_area, by.x = "bbl__10_digits", by.y = "bbl")

df_build_energy$ghg <- as.numeric(df_build_energy$total_ghg_emissions_metric_tons_co2e_)
df_build_energy = filter(df_build_energy, ghg >= 0) 

df_build_energy$borough = df_build_energy$borough.y

df_ghg <- df_build_energy %>% 
  group_by(borough, zip) %>% 
  summarise(avg_ghg = mean(ghg), median_ghg = median(ghg))

df_ghg$place <- paste(df_ghg$borough, df_ghg$zip, sep = " - ")
```
