# Data transformation

# get data frames from sheets
```{r}
# from melissa_data_sets/evaluate_ny/resources.xlsx
ev_charging_use_data = resources_sheets$`Charging Use`
ev_rebate_eligible_cars_data = resources_sheets$`Rebate Lookup`

# from melissa_data_sets/evaluate_ny/EV-Registration-Tables.xlsx
ev_zip_code_data = ev_registration_tables_sheets$`Current by ZIP Code`
ev_make_model_data = ev_registration_tables_sheets$`Current by Make-Model`
ev_county_data = ev_registration_tables_sheets$`Current by County`
ev_over_time_data = ev_registration_tables_sheets$`Original Over Time`
ev_make_over_time = ev_registration_tables_sheets$`Original by Make`
```

```{r}
cleanCols <- function(x){
  lower_names = tolower(names(x))
  sub_periods = gsub("\\.", "_", lower_names)
  clean_df_cols = gsub("__","_",sub_periods)
  return(clean_df_cols)
}
```

# rename cols
```{r}
names(global_electric_car_sales_data) = cleanCols(global_electric_car_sales_data)
names(energy_programs_data) = cleanCols(energy_programs_data)
names(emissions_from_fuel_data) = cleanCols(emissions_from_fuel_data)
names(fuel_emission_factors_data) = cleanCols(fuel_emission_factors_data)
names(clean_rebate_data) = cleanCols(clean_rebate_data)
```

# var cleaning
```{r}
clean_rebate_data$year = 
```

